name: TestLinting

on:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Scheduled test'
        type: boolean

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint

      - name: Print tag if present
        run: |
          echo "Tags: $TAGS"
        env:
          TAGS: ${{ github.event.inputs.tags }}
